// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKy1u_-KGlauq5RpCWC5EtzAeHVIwpv8k',
    appId: '1:27968507797:web:1055fb737a9a635047b09c',
    messagingSenderId: '27968507797',
    projectId: 'chat-app-303ff',
    authDomain: 'chat-app-303ff.firebaseapp.com',
    storageBucket: 'chat-app-303ff.appspot.com',
    measurementId: 'G-CX3HBPL842',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbWfWyeFKA_tH8-TxyU8lmRiESe_9UX_E',
    appId: '1:27968507797:android:3fe46a506774061c47b09c',
    messagingSenderId: '27968507797',
    projectId: 'chat-app-303ff',
    storageBucket: 'chat-app-303ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqpwwcJXWVumaKEoEDx97p86OJzV8qhkk',
    appId: '1:27968507797:ios:3d08700c444aa50047b09c',
    messagingSenderId: '27968507797',
    projectId: 'chat-app-303ff',
    storageBucket: 'chat-app-303ff.appspot.com',
    iosBundleId: 'com.example.chatingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqpwwcJXWVumaKEoEDx97p86OJzV8qhkk',
    appId: '1:27968507797:ios:3d08700c444aa50047b09c',
    messagingSenderId: '27968507797',
    projectId: 'chat-app-303ff',
    storageBucket: 'chat-app-303ff.appspot.com',
    iosBundleId: 'com.example.chatingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKy1u_-KGlauq5RpCWC5EtzAeHVIwpv8k',
    appId: '1:27968507797:web:88857ece8aa56a7747b09c',
    messagingSenderId: '27968507797',
    projectId: 'chat-app-303ff',
    authDomain: 'chat-app-303ff.firebaseapp.com',
    storageBucket: 'chat-app-303ff.appspot.com',
    measurementId: 'G-CFCNJSPLHX',
  );
}
